apiVersion: k8s.aws/v1alpha1
kind: DeviceConfig
metadata:
  labels:
    app.kubernetes.io/name: deviceconfig
    app.kubernetes.io/instance: deviceconfig-sample
    app.kubernetes.io/part-of: operator-for-ai-chips-on-aws
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-for-ai-chips-on-aws
  name: deviceconfig-sample
spec:
  # TODO(user): Add fields here
