apiVersion: k8s.aws/v1alpha1
kind: DeviceConfig
metadata:
  name: device-config
  namespace:  ai-operator-on-aws
spec:
  useInTreeDrivers: false
  driversImage: public.ecr.aws/os-partners/neuron-openshift/neuron-kernel-module:2.24.7.0
  devicePluginImage: public.ecr.aws/neuron/neuron-device-plugin:2.24.23.0
  customSchedulerImage: public.ecr.aws/eks-distro/kubernetes/kube-scheduler:v1.32.9-eks-1-32-24
  schedulerExtensionImage: public.ecr.aws/neuron/neuron-scheduler:2.24.23.0
  nodeMetricsImage: public.ecr.aws/neuron/neuron-monitor:1.3.0
  selector:
    feature.node.kubernetes.io/aws-neuron: "true"
